[package]
name = "reckless_cmd"
version = "0.0.1-alpha.1"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "3.2.19", features = ["derive"] }
async-trait = "0.1.57"
reckless_lib = { path = "../reckless_lib" }
