[package]
name = "coffee_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.22.0", features = ["rt"] }
coffee_core = { path = "../coffee_core" }
serde_json = "1"
serde = "1.0.159"
cln-plugin = "0.1.3"
anyhow = "1.0.70"
